# ####################################################################################
# ///// HYPRPAPER CONFIGURATION
# ####################################################################################

# --- Configurações Gerais ---
splash = false
ipc = true

# --- Configuração do Wallpaper ---

# Exemplo para Monitor Específico (Substitua DP-1 pela sua saída)
wallpaper {
    monitor = DP-1
    path = ~/wallpapers/NOME_DO_WALLPAPER.jpg
    fit_mode = cover
}

# --- Configuração de Fallback (Aplica a qualquer monitor não especificado) ---
wallpaper {
    monitor =
    path = ~/wallpapers/NOME_DO_WALLPAPER.jpg
    fit_mode = cover
}

# --- Exemplo apontando para uma PASTA (Muda de wallpaper automaticamente!) ---
# wallpaper {
#     monitor = DP-2
#     path = ~/wallpapers/
#     fit_mode = cover
#     timeout = 60
#     order = random
#     recursive = false
# }